### ISSUE TITLE
Cannot connect with Metamask

### ISSUE THREAD

**Issue by lakshyabatman** [Shmoji/web3-react-example#2]
https://user-images.githubusercontent.com/29687362/145731585-3ee32ff5-c9cc-4f22-b746-ec4d1930264a.mov

Hello @Shmoji , I'm not able to connect with metamask. I've legit copied the same code as in medium blog

**Comment by letrii** [comment]
I have same error :(

**Comment by nicotrozzo** [comment]
Have you installed and connected to your Metamask wallet? 
[Metamask Chrome Extension](https://chrome.google.com/webstore/detail/metamask/nkbihfbeogaeaoehlefnkodbefgpgknn)

**Comment by Shmoji** [comment]
@lakshyabatman @letrii make sure you are connected to the Ethereum Mainnet network in MetaMask

**Comment by lakshyabatman** [comment]
Yep, it's working now. Thanks! I messed up my code.
